host:
    addr:   '192.168.2.44'
    name:   'raspberrypi'
    user:   'pi'

button:
    gpio:   17
    
leds:
    -
        color: 'red'
        gpio:   27
    -
        color: 'yellow'
        gpio:   26
